# data
catalog_path: ../data/catalog/catalog_v3.csv
data_path: ../data/pretrain_data
save_checkpoint_path: ../data/checkpoints/clip/pretrained
load_checkpoint_path: ../data/checkpoints/clip/pretrained
load_checkpoint_mode: skip  # skip, last or filename
load_checkpoint_filename: 
valid_split: 0.0
valid_batch_size: 128

# external models
external_models_ckpt_path: ../data/checkpoints/external_models
image_ckpt_filename: 3DGrid-VQGAN_43.pt
image_embedding: 2048
text_ckpt_filename: smi-ted-Light_40.pt
text_embedding: 768

# model
pretrained: True  # for both image encoder and text encoder
trainable: False  # for both image encoder and text encoder
temperature: 1.0
train_step: epoch
size: 128  # image size
num_projection_layers: 1
projection_dim: 512 
dropout: 0.1

# run
max_epochs: 101
batch_size: 128
num_workers: 2
head_lr: 3e-4
image_encoder_lr: 1e-4
text_encoder_lr: 1e-5
weight_decay: 1e-3
patience: 2
factor: 0.5
save_every_steps: .inf